export const OrderBillPaymentsStatus = {
  PENDENTE_APROVACAO: 'PENDENTE_APROVACAO',
  PEDIDO_APROVADO: 'PEDIDO_APROVADO',
  PEDIDO_CANCELADO: 'PEDIDO_CANCELADO',
  AGUARDANDO_PAGAMENTO_TARIFA: 'AGUARDANDO_PAGAMENTO_TARIFA',
  PAGAMENTO_TARIFA_REALIZADO: 'PAGAMENTO_TARIFA_REALIZADO',
  AGUARDANDO_EXECUCAO_PAGAMENTO: 'AGUARDANDO_EXECUCAO_PAGAMENTO',
  EM_PROCESSAMENTO: 'EM_PROCESSAMENTO',
  PEDIDO_FINALIZADO: 'PEDIDO_FINALIZADO',
  PEDIDO_FINALIZADO_ERROR: 'PEDIDO_FINALIZADO_ERROR'
} as const;

export type OrderBillPaymentsStatusEnum = keyof typeof OrderBillPaymentsStatus;
